apiVersion: v1
kind: ResourceQuota
metadata:
  name: portfolio-resource-quota
  namespace: portfolio
spec:
  hard:
    requests.cpu: "2"   
    requests.memory: "4Gi" 
    limits.cpu: "3"  
    limits.memory: "6Gi"  
