apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: portfolio
  name: portfolio-rolebinding
subjects:
- kind: User
  name: theofil888@gmail.com 
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: admin
  apiGroup: rbac.authorization.k8s.io
