apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: portfolio
  name: readonly-binding
subjects:
- kind: User
  name: readonly-user@example.com 
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: readonly-role
  apiGroup: rbac.authorization.k8s.io
